from fpdf import FPDF
import datetime

class HealthReportPDF(FPDF):
    def header(self):
        self.set_font('Arial', 'B', 15)
        self.cell(80)
        self.cell(30, 10, 'RuralHealth AI - Health Report', 0, 0, 'C')
        self.ln(20)

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.cell(0, 10, 'Page ' + str(self.page_no()) + '/{nb}', 0, 0, 'C')

def generate_pdf(user_name, prediction_data):
    pdf = HealthReportPDF()
    pdf.alias_nb_pages()
    pdf.add_page()
    pdf.set_font('Arial', '', 12)
    
    pdf.cell(0, 10, f'Patient Name: {user_name}', 0, 1)
    pdf.cell(0, 10, f'Date: {datetime.datetime.now().strftime("%Y-%m-%d %H:%M")}', 0, 1)
    pdf.ln(10)
    
    pdf.set_font('Arial', 'B', 12)
    pdf.cell(0, 10, f"Predicted Condition: {prediction_data['disease']} ({prediction_data['confidence']:.1f}%)", 0, 1)
    pdf.cell(0, 10, f"Severity: {prediction_data['severity']}", 0, 1)
    pdf.ln(5)
    
    pdf.set_font('Arial', '', 12)
    pdf.multi_cell(0, 10, f"Description (En): {prediction_data['description']['en']}")
    pdf.ln(5)
    
    # Precautions
    pdf.ln(5)
    pdf.set_font('Arial', 'B', 12)
    pdf.cell(0, 10, "Precautions:", 0, 1)
    pdf.set_font('Arial', '', 12)
    
    precautions = prediction_data.get('precautions', [])
    if isinstance(precautions, list):
        for i, p in enumerate(precautions, 1):
            # Default to English for PDF for now, or use mapped value if needed
            text = p.get('en', 'Consult a doctor')
            pdf.cell(0, 8, f"{i}. {text}", ln=True)
    elif isinstance(precautions, dict):
         # Fallback for old structure
         text = precautions.get('en', 'Consult a doctor')
         pdf.cell(0, 8, f"- {text}", ln=True)
    else:
         pdf.cell(0, 8, "Consult a doctor", ln=True)
    
    pdf.ln(5)
    
    pdf.ln(10)
    pdf.set_font('Arial', 'I', 10)
    pdf.multi_cell(0, 10, "Disclaimer: This report is generated by AI and is not a substitute for professional medical advice. Please consult a doctor.")
    
    filename = f"report_{user_name}_{datetime.datetime.now().strftime('%Y%m%d%H%M')}.pdf"
    # Ensure reports dir exists
    # pdf.output(f"./reports/{filename}", 'F') # Save to disk
    return pdf.output(dest='S').encode('latin-1') # Return bytes
